<<<<<<< HEAD
[build]
  command = "bun install && bun run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[images]
  remote_images = ["https://same-assets.com/*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Explicitly enable Netlify Blobs for serverless functions
[blobs]
  [blobs.signals]
    store = "signals"
=======
[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
>>>>>>> 09fbac6 (Phase 1: Rebuild /api, Blob, Admin ChatPanel, artefact bridge logic (no artefact or legacy blob overwrite))
